/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as SignupInviteRouteImport } from './routes/signup_.invite'
import { Route as SignupVerifyEmailRouteImport } from './routes/signup_.verify-email'
import { Route as ShellAdminIndexRouteImport } from './routes/_shell/admin/index'
import { Route as ShellAssistantIndexRouteImport } from './routes/_shell/assistant/index'
import { Route as ShellCalendarIndexRouteImport } from './routes/_shell/calendar/index'
import { Route as ShellChatIndexRouteImport } from './routes/_shell/chat/index'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs/index'
import { Route as ShellDocsDocumentIdRouteImport } from './routes/_shell/docs/$documentId'
import { Route as ShellDriveIndexRouteImport } from './routes/_shell/drive/index'
import { Route as ShellMailIndexRouteImport } from './routes/_shell/mail/index'
import { Route as ShellMediaObjectIdRouteImport } from './routes/_shell/media/$objectId'
import { Route as ShellMeetIndexRouteImport } from './routes/_shell/meet/index'
import { Route as ShellOnboardingIndexRouteImport } from './routes/_shell/onboarding/index'
import { Route as ShellOpenObjectIdRouteImport } from './routes/_shell/open/$objectId'
import { Route as ShellPdfObjectIdRouteImport } from './routes/_shell/pdf/$objectId'
import { Route as ShellSheetsIndexRouteImport } from './routes/_shell/sheets/index'
import { Route as ShellSlidesIndexRouteImport } from './routes/_shell/slides/index'
import { Route as ShellWelcomeIndexRouteImport } from './routes/_shell/welcome/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupInviteRoute = SignupInviteRouteImport.update({
  id: '/signup_/invite',
  path: '/signup/invite',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupVerifyEmailRoute = SignupVerifyEmailRouteImport.update({
  id: '/signup_/verify-email',
  path: '/signup/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdminIndexRoute = ShellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistantIndexRoute = ShellAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarIndexRoute = ShellCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatIndexRoute = ShellChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsDocumentIdRoute = ShellDocsDocumentIdRouteImport.update({
  id: '/docs/$documentId',
  path: '/docs/$documentId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDriveIndexRoute = ShellDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMailIndexRoute = ShellMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMediaObjectIdRoute = ShellMediaObjectIdRouteImport.update({
  id: '/media/$objectId',
  path: '/media/$objectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeetIndexRoute = ShellMeetIndexRouteImport.update({
  id: '/meet/',
  path: '/meet/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOnboardingIndexRoute = ShellOnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellOpenObjectIdRoute = ShellOpenObjectIdRouteImport.update({
  id: '/open/$objectId',
  path: '/open/$objectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellPdfObjectIdRoute = ShellPdfObjectIdRouteImport.update({
  id: '/pdf/$objectId',
  path: '/pdf/$objectId',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSheetsIndexRoute = ShellSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSlidesIndexRoute = ShellSlidesIndexRouteImport.update({
  id: '/slides/',
  path: '/slides/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellWelcomeIndexRoute = ShellWelcomeIndexRouteImport.update({
  id: '/welcome/',
  path: '/welcome/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signup/invite': typeof SignupInviteRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/docs/$documentId': typeof ShellDocsDocumentIdRoute
  '/media/$objectId': typeof ShellMediaObjectIdRoute
  '/open/$objectId': typeof ShellOpenObjectIdRoute
  '/pdf/$objectId': typeof ShellPdfObjectIdRoute
  '/admin/': typeof ShellAdminIndexRoute
  '/assistant/': typeof ShellAssistantIndexRoute
  '/calendar/': typeof ShellCalendarIndexRoute
  '/chat/': typeof ShellChatIndexRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/drive/': typeof ShellDriveIndexRoute
  '/mail/': typeof ShellMailIndexRoute
  '/meet/': typeof ShellMeetIndexRoute
  '/onboarding/': typeof ShellOnboardingIndexRoute
  '/sheets/': typeof ShellSheetsIndexRoute
  '/slides/': typeof ShellSlidesIndexRoute
  '/welcome/': typeof ShellWelcomeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signup/invite': typeof SignupInviteRoute
  '/signup/verify-email': typeof SignupVerifyEmailRoute
  '/docs/$documentId': typeof ShellDocsDocumentIdRoute
  '/media/$objectId': typeof ShellMediaObjectIdRoute
  '/open/$objectId': typeof ShellOpenObjectIdRoute
  '/pdf/$objectId': typeof ShellPdfObjectIdRoute
  '/admin': typeof ShellAdminIndexRoute
  '/assistant': typeof ShellAssistantIndexRoute
  '/calendar': typeof ShellCalendarIndexRoute
  '/chat': typeof ShellChatIndexRoute
  '/docs': typeof ShellDocsIndexRoute
  '/drive': typeof ShellDriveIndexRoute
  '/mail': typeof ShellMailIndexRoute
  '/meet': typeof ShellMeetIndexRoute
  '/onboarding': typeof ShellOnboardingIndexRoute
  '/sheets': typeof ShellSheetsIndexRoute
  '/slides': typeof ShellSlidesIndexRoute
  '/welcome': typeof ShellWelcomeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/signup_/invite': typeof SignupInviteRoute
  '/signup_/verify-email': typeof SignupVerifyEmailRoute
  '/_shell/docs/$documentId': typeof ShellDocsDocumentIdRoute
  '/_shell/media/$objectId': typeof ShellMediaObjectIdRoute
  '/_shell/open/$objectId': typeof ShellOpenObjectIdRoute
  '/_shell/pdf/$objectId': typeof ShellPdfObjectIdRoute
  '/_shell/admin/': typeof ShellAdminIndexRoute
  '/_shell/assistant/': typeof ShellAssistantIndexRoute
  '/_shell/calendar/': typeof ShellCalendarIndexRoute
  '/_shell/chat/': typeof ShellChatIndexRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/drive/': typeof ShellDriveIndexRoute
  '/_shell/mail/': typeof ShellMailIndexRoute
  '/_shell/meet/': typeof ShellMeetIndexRoute
  '/_shell/onboarding/': typeof ShellOnboardingIndexRoute
  '/_shell/sheets/': typeof ShellSheetsIndexRoute
  '/_shell/slides/': typeof ShellSlidesIndexRoute
  '/_shell/welcome/': typeof ShellWelcomeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/signup/invite'
    | '/signup/verify-email'
    | '/docs/$documentId'
    | '/media/$objectId'
    | '/open/$objectId'
    | '/pdf/$objectId'
    | '/admin/'
    | '/assistant/'
    | '/calendar/'
    | '/chat/'
    | '/docs/'
    | '/drive/'
    | '/mail/'
    | '/meet/'
    | '/onboarding/'
    | '/sheets/'
    | '/slides/'
    | '/welcome/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/signup/invite'
    | '/signup/verify-email'
    | '/docs/$documentId'
    | '/media/$objectId'
    | '/open/$objectId'
    | '/pdf/$objectId'
    | '/admin'
    | '/assistant'
    | '/calendar'
    | '/chat'
    | '/docs'
    | '/drive'
    | '/mail'
    | '/meet'
    | '/onboarding'
    | '/sheets'
    | '/slides'
    | '/welcome'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/signup_/invite'
    | '/signup_/verify-email'
    | '/_shell/docs/$documentId'
    | '/_shell/media/$objectId'
    | '/_shell/open/$objectId'
    | '/_shell/pdf/$objectId'
    | '/_shell/admin/'
    | '/_shell/assistant/'
    | '/_shell/calendar/'
    | '/_shell/chat/'
    | '/_shell/docs/'
    | '/_shell/drive/'
    | '/_shell/mail/'
    | '/_shell/meet/'
    | '/_shell/onboarding/'
    | '/_shell/sheets/'
    | '/_shell/slides/'
    | '/_shell/welcome/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OauthConsentRoute: typeof OauthConsentRoute
  SignupInviteRoute: typeof SignupInviteRoute
  SignupVerifyEmailRoute: typeof SignupVerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/invite': {
      id: '/signup_/invite'
      path: '/signup/invite'
      fullPath: '/signup/invite'
      preLoaderRoute: typeof SignupInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup_/verify-email': {
      id: '/signup_/verify-email'
      path: '/signup/verify-email'
      fullPath: '/signup/verify-email'
      preLoaderRoute: typeof SignupVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/admin/': {
      id: '/_shell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ShellAdminIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant/': {
      id: '/_shell/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ShellAssistantIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar/': {
      id: '/_shell/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof ShellCalendarIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/': {
      id: '/_shell/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ShellChatIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/$documentId': {
      id: '/_shell/docs/$documentId'
      path: '/docs/$documentId'
      fullPath: '/docs/$documentId'
      preLoaderRoute: typeof ShellDocsDocumentIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/drive/': {
      id: '/_shell/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof ShellDriveIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mail/': {
      id: '/_shell/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof ShellMailIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/media/$objectId': {
      id: '/_shell/media/$objectId'
      path: '/media/$objectId'
      fullPath: '/media/$objectId'
      preLoaderRoute: typeof ShellMediaObjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meet/': {
      id: '/_shell/meet/'
      path: '/meet'
      fullPath: '/meet/'
      preLoaderRoute: typeof ShellMeetIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/onboarding/': {
      id: '/_shell/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof ShellOnboardingIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/open/$objectId': {
      id: '/_shell/open/$objectId'
      path: '/open/$objectId'
      fullPath: '/open/$objectId'
      preLoaderRoute: typeof ShellOpenObjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/pdf/$objectId': {
      id: '/_shell/pdf/$objectId'
      path: '/pdf/$objectId'
      fullPath: '/pdf/$objectId'
      preLoaderRoute: typeof ShellPdfObjectIdRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sheets/': {
      id: '/_shell/sheets/'
      path: '/sheets'
      fullPath: '/sheets/'
      preLoaderRoute: typeof ShellSheetsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/slides/': {
      id: '/_shell/slides/'
      path: '/slides'
      fullPath: '/slides/'
      preLoaderRoute: typeof ShellSlidesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/welcome/': {
      id: '/_shell/welcome/'
      path: '/welcome'
      fullPath: '/welcome/'
      preLoaderRoute: typeof ShellWelcomeIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDocsDocumentIdRoute: typeof ShellDocsDocumentIdRoute
  ShellMediaObjectIdRoute: typeof ShellMediaObjectIdRoute
  ShellOpenObjectIdRoute: typeof ShellOpenObjectIdRoute
  ShellPdfObjectIdRoute: typeof ShellPdfObjectIdRoute
  ShellAdminIndexRoute: typeof ShellAdminIndexRoute
  ShellAssistantIndexRoute: typeof ShellAssistantIndexRoute
  ShellCalendarIndexRoute: typeof ShellCalendarIndexRoute
  ShellChatIndexRoute: typeof ShellChatIndexRoute
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellDriveIndexRoute: typeof ShellDriveIndexRoute
  ShellMailIndexRoute: typeof ShellMailIndexRoute
  ShellMeetIndexRoute: typeof ShellMeetIndexRoute
  ShellOnboardingIndexRoute: typeof ShellOnboardingIndexRoute
  ShellSheetsIndexRoute: typeof ShellSheetsIndexRoute
  ShellSlidesIndexRoute: typeof ShellSlidesIndexRoute
  ShellWelcomeIndexRoute: typeof ShellWelcomeIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDocsDocumentIdRoute: ShellDocsDocumentIdRoute,
  ShellMediaObjectIdRoute: ShellMediaObjectIdRoute,
  ShellOpenObjectIdRoute: ShellOpenObjectIdRoute,
  ShellPdfObjectIdRoute: ShellPdfObjectIdRoute,
  ShellAdminIndexRoute: ShellAdminIndexRoute,
  ShellAssistantIndexRoute: ShellAssistantIndexRoute,
  ShellCalendarIndexRoute: ShellCalendarIndexRoute,
  ShellChatIndexRoute: ShellChatIndexRoute,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellDriveIndexRoute: ShellDriveIndexRoute,
  ShellMailIndexRoute: ShellMailIndexRoute,
  ShellMeetIndexRoute: ShellMeetIndexRoute,
  ShellOnboardingIndexRoute: ShellOnboardingIndexRoute,
  ShellSheetsIndexRoute: ShellSheetsIndexRoute,
  ShellSlidesIndexRoute: ShellSlidesIndexRoute,
  ShellWelcomeIndexRoute: ShellWelcomeIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OauthConsentRoute: OauthConsentRoute,
  SignupInviteRoute: SignupInviteRoute,
  SignupVerifyEmailRoute: SignupVerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
