/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as ShellSlidesIndexRouteImport } from './routes/_shell/slides/index'
import { Route as ShellSheetsIndexRouteImport } from './routes/_shell/sheets/index'
import { Route as ShellMeetIndexRouteImport } from './routes/_shell/meet/index'
import { Route as ShellMailIndexRouteImport } from './routes/_shell/mail/index'
import { Route as ShellDriveIndexRouteImport } from './routes/_shell/drive/index'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs/index'
import { Route as ShellChatIndexRouteImport } from './routes/_shell/chat/index'
import { Route as ShellCalendarIndexRouteImport } from './routes/_shell/calendar/index'
import { Route as ShellAssistantIndexRouteImport } from './routes/_shell/assistant/index'
import { Route as ShellAdminIndexRouteImport } from './routes/_shell/admin/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSlidesIndexRoute = ShellSlidesIndexRouteImport.update({
  id: '/slides/',
  path: '/slides/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSheetsIndexRoute = ShellSheetsIndexRouteImport.update({
  id: '/sheets/',
  path: '/sheets/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMeetIndexRoute = ShellMeetIndexRouteImport.update({
  id: '/meet/',
  path: '/meet/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellMailIndexRoute = ShellMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDriveIndexRoute = ShellDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellChatIndexRoute = ShellChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCalendarIndexRoute = ShellCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAssistantIndexRoute = ShellAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminIndexRoute = ShellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin/': typeof ShellAdminIndexRoute
  '/assistant/': typeof ShellAssistantIndexRoute
  '/calendar/': typeof ShellCalendarIndexRoute
  '/chat/': typeof ShellChatIndexRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/drive/': typeof ShellDriveIndexRoute
  '/mail/': typeof ShellMailIndexRoute
  '/meet/': typeof ShellMeetIndexRoute
  '/sheets/': typeof ShellSheetsIndexRoute
  '/slides/': typeof ShellSlidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/admin': typeof ShellAdminIndexRoute
  '/assistant': typeof ShellAssistantIndexRoute
  '/calendar': typeof ShellCalendarIndexRoute
  '/chat': typeof ShellChatIndexRoute
  '/docs': typeof ShellDocsIndexRoute
  '/drive': typeof ShellDriveIndexRoute
  '/mail': typeof ShellMailIndexRoute
  '/meet': typeof ShellMeetIndexRoute
  '/sheets': typeof ShellSheetsIndexRoute
  '/slides': typeof ShellSlidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_shell/admin/': typeof ShellAdminIndexRoute
  '/_shell/assistant/': typeof ShellAssistantIndexRoute
  '/_shell/calendar/': typeof ShellCalendarIndexRoute
  '/_shell/chat/': typeof ShellChatIndexRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/drive/': typeof ShellDriveIndexRoute
  '/_shell/mail/': typeof ShellMailIndexRoute
  '/_shell/meet/': typeof ShellMeetIndexRoute
  '/_shell/sheets/': typeof ShellSheetsIndexRoute
  '/_shell/slides/': typeof ShellSlidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/oauth/consent'
    | '/admin/'
    | '/assistant/'
    | '/calendar/'
    | '/chat/'
    | '/docs/'
    | '/drive/'
    | '/mail/'
    | '/meet/'
    | '/sheets/'
    | '/slides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/oauth/consent'
    | '/admin'
    | '/assistant'
    | '/calendar'
    | '/chat'
    | '/docs'
    | '/drive'
    | '/mail'
    | '/meet'
    | '/sheets'
    | '/slides'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/oauth/consent'
    | '/_shell/admin/'
    | '/_shell/assistant/'
    | '/_shell/calendar/'
    | '/_shell/chat/'
    | '/_shell/docs/'
    | '/_shell/drive/'
    | '/_shell/mail/'
    | '/_shell/meet/'
    | '/_shell/sheets/'
    | '/_shell/slides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/slides/': {
      id: '/_shell/slides/'
      path: '/slides'
      fullPath: '/slides/'
      preLoaderRoute: typeof ShellSlidesIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/sheets/': {
      id: '/_shell/sheets/'
      path: '/sheets'
      fullPath: '/sheets/'
      preLoaderRoute: typeof ShellSheetsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meet/': {
      id: '/_shell/meet/'
      path: '/meet'
      fullPath: '/meet/'
      preLoaderRoute: typeof ShellMeetIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mail/': {
      id: '/_shell/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof ShellMailIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/drive/': {
      id: '/_shell/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof ShellDriveIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/': {
      id: '/_shell/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ShellChatIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar/': {
      id: '/_shell/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof ShellCalendarIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant/': {
      id: '/_shell/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ShellAssistantIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/': {
      id: '/_shell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ShellAdminIndexRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellAdminIndexRoute: typeof ShellAdminIndexRoute
  ShellAssistantIndexRoute: typeof ShellAssistantIndexRoute
  ShellCalendarIndexRoute: typeof ShellCalendarIndexRoute
  ShellChatIndexRoute: typeof ShellChatIndexRoute
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellDriveIndexRoute: typeof ShellDriveIndexRoute
  ShellMailIndexRoute: typeof ShellMailIndexRoute
  ShellMeetIndexRoute: typeof ShellMeetIndexRoute
  ShellSheetsIndexRoute: typeof ShellSheetsIndexRoute
  ShellSlidesIndexRoute: typeof ShellSlidesIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellAdminIndexRoute: ShellAdminIndexRoute,
  ShellAssistantIndexRoute: ShellAssistantIndexRoute,
  ShellCalendarIndexRoute: ShellCalendarIndexRoute,
  ShellChatIndexRoute: ShellChatIndexRoute,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellDriveIndexRoute: ShellDriveIndexRoute,
  ShellMailIndexRoute: ShellMailIndexRoute,
  ShellMeetIndexRoute: ShellMeetIndexRoute,
  ShellSheetsIndexRoute: ShellSheetsIndexRoute,
  ShellSlidesIndexRoute: ShellSlidesIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
