/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OauthConsentRouteImport } from './routes/oauth.consent'
import { Route as ShellSettingsIndexRouteImport } from './routes/_shell/settings/index'
import { Route as ShellSearchIndexRouteImport } from './routes/_shell/search/index'
import { Route as ShellMeetIndexRouteImport } from './routes/_shell/meet/index'
import { Route as ShellMailIndexRouteImport } from './routes/_shell/mail/index'
import { Route as ShellDriveIndexRouteImport } from './routes/_shell/drive/index'
import { Route as ShellDocsIndexRouteImport } from './routes/_shell/docs/index'
import { Route as ShellChatIndexRouteImport } from './routes/_shell/chat/index'
import { Route as ShellCalendarIndexRouteImport } from './routes/_shell/calendar/index'
import { Route as ShellAssistantIndexRouteImport } from './routes/_shell/assistant/index'
import { Route as ShellAdminIndexRouteImport } from './routes/_shell/admin/index'
import { Route as ShellSettingsAdminRouteImport } from './routes/_shell/settings/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthConsentRoute = OauthConsentRouteImport.update({
  id: '/oauth/consent',
  path: '/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellSettingsIndexRoute = ShellSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/settings/index.lazy').then((d) => d.Route),
)
const ShellSearchIndexRoute = ShellSearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/search/index.lazy').then((d) => d.Route),
)
const ShellMeetIndexRoute = ShellMeetIndexRouteImport.update({
  id: '/meet/',
  path: '/meet/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/meet/index.lazy').then((d) => d.Route),
)
const ShellMailIndexRoute = ShellMailIndexRouteImport.update({
  id: '/mail/',
  path: '/mail/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/mail/index.lazy').then((d) => d.Route),
)
const ShellDriveIndexRoute = ShellDriveIndexRouteImport.update({
  id: '/drive/',
  path: '/drive/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/drive/index.lazy').then((d) => d.Route),
)
const ShellDocsIndexRoute = ShellDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/docs/index.lazy').then((d) => d.Route),
)
const ShellChatIndexRoute = ShellChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/chat/index.lazy').then((d) => d.Route),
)
const ShellCalendarIndexRoute = ShellCalendarIndexRouteImport.update({
  id: '/calendar/',
  path: '/calendar/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/calendar/index.lazy').then((d) => d.Route),
)
const ShellAssistantIndexRoute = ShellAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/assistant/index.lazy').then((d) => d.Route),
)
const ShellAdminIndexRoute = ShellAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/admin/index.lazy').then((d) => d.Route),
)
const ShellSettingsAdminRoute = ShellSettingsAdminRouteImport.update({
  id: '/settings/admin',
  path: '/settings/admin',
  getParentRoute: () => ShellRoute,
} as any).lazy(() =>
  import('./routes/_shell/settings/admin.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/settings/admin': typeof ShellSettingsAdminRoute
  '/admin/': typeof ShellAdminIndexRoute
  '/assistant/': typeof ShellAssistantIndexRoute
  '/calendar/': typeof ShellCalendarIndexRoute
  '/chat/': typeof ShellChatIndexRoute
  '/docs/': typeof ShellDocsIndexRoute
  '/drive/': typeof ShellDriveIndexRoute
  '/mail/': typeof ShellMailIndexRoute
  '/meet/': typeof ShellMeetIndexRoute
  '/search/': typeof ShellSearchIndexRoute
  '/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/settings/admin': typeof ShellSettingsAdminRoute
  '/admin': typeof ShellAdminIndexRoute
  '/assistant': typeof ShellAssistantIndexRoute
  '/calendar': typeof ShellCalendarIndexRoute
  '/chat': typeof ShellChatIndexRoute
  '/docs': typeof ShellDocsIndexRoute
  '/drive': typeof ShellDriveIndexRoute
  '/mail': typeof ShellMailIndexRoute
  '/meet': typeof ShellMeetIndexRoute
  '/search': typeof ShellSearchIndexRoute
  '/settings': typeof ShellSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/oauth/consent': typeof OauthConsentRoute
  '/_shell/settings/admin': typeof ShellSettingsAdminRoute
  '/_shell/admin/': typeof ShellAdminIndexRoute
  '/_shell/assistant/': typeof ShellAssistantIndexRoute
  '/_shell/calendar/': typeof ShellCalendarIndexRoute
  '/_shell/chat/': typeof ShellChatIndexRoute
  '/_shell/docs/': typeof ShellDocsIndexRoute
  '/_shell/drive/': typeof ShellDriveIndexRoute
  '/_shell/mail/': typeof ShellMailIndexRoute
  '/_shell/meet/': typeof ShellMeetIndexRoute
  '/_shell/search/': typeof ShellSearchIndexRoute
  '/_shell/settings/': typeof ShellSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/settings/admin'
    | '/admin/'
    | '/assistant/'
    | '/calendar/'
    | '/chat/'
    | '/docs/'
    | '/drive/'
    | '/mail/'
    | '/meet/'
    | '/search/'
    | '/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/settings/admin'
    | '/admin'
    | '/assistant'
    | '/calendar'
    | '/chat'
    | '/docs'
    | '/drive'
    | '/mail'
    | '/meet'
    | '/search'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/login'
    | '/signup'
    | '/oauth/consent'
    | '/_shell/settings/admin'
    | '/_shell/admin/'
    | '/_shell/assistant/'
    | '/_shell/calendar/'
    | '/_shell/chat/'
    | '/_shell/docs/'
    | '/_shell/drive/'
    | '/_shell/mail/'
    | '/_shell/meet/'
    | '/_shell/search/'
    | '/_shell/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  OauthConsentRoute: typeof OauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/consent': {
      id: '/oauth/consent'
      path: '/oauth/consent'
      fullPath: '/oauth/consent'
      preLoaderRoute: typeof OauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/settings/': {
      id: '/_shell/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ShellSettingsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/search/': {
      id: '/_shell/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof ShellSearchIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/meet/': {
      id: '/_shell/meet/'
      path: '/meet'
      fullPath: '/meet/'
      preLoaderRoute: typeof ShellMeetIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/mail/': {
      id: '/_shell/mail/'
      path: '/mail'
      fullPath: '/mail/'
      preLoaderRoute: typeof ShellMailIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/drive/': {
      id: '/_shell/drive/'
      path: '/drive'
      fullPath: '/drive/'
      preLoaderRoute: typeof ShellDriveIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/docs/': {
      id: '/_shell/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof ShellDocsIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/chat/': {
      id: '/_shell/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof ShellChatIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/calendar/': {
      id: '/_shell/calendar/'
      path: '/calendar'
      fullPath: '/calendar/'
      preLoaderRoute: typeof ShellCalendarIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/assistant/': {
      id: '/_shell/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof ShellAssistantIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/': {
      id: '/_shell/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof ShellAdminIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings/admin': {
      id: '/_shell/settings/admin'
      path: '/settings/admin'
      fullPath: '/settings/admin'
      preLoaderRoute: typeof ShellSettingsAdminRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellSettingsAdminRoute: typeof ShellSettingsAdminRoute
  ShellAdminIndexRoute: typeof ShellAdminIndexRoute
  ShellAssistantIndexRoute: typeof ShellAssistantIndexRoute
  ShellCalendarIndexRoute: typeof ShellCalendarIndexRoute
  ShellChatIndexRoute: typeof ShellChatIndexRoute
  ShellDocsIndexRoute: typeof ShellDocsIndexRoute
  ShellDriveIndexRoute: typeof ShellDriveIndexRoute
  ShellMailIndexRoute: typeof ShellMailIndexRoute
  ShellMeetIndexRoute: typeof ShellMeetIndexRoute
  ShellSearchIndexRoute: typeof ShellSearchIndexRoute
  ShellSettingsIndexRoute: typeof ShellSettingsIndexRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellSettingsAdminRoute: ShellSettingsAdminRoute,
  ShellAdminIndexRoute: ShellAdminIndexRoute,
  ShellAssistantIndexRoute: ShellAssistantIndexRoute,
  ShellCalendarIndexRoute: ShellCalendarIndexRoute,
  ShellChatIndexRoute: ShellChatIndexRoute,
  ShellDocsIndexRoute: ShellDocsIndexRoute,
  ShellDriveIndexRoute: ShellDriveIndexRoute,
  ShellMailIndexRoute: ShellMailIndexRoute,
  ShellMeetIndexRoute: ShellMeetIndexRoute,
  ShellSearchIndexRoute: ShellSearchIndexRoute,
  ShellSettingsIndexRoute: ShellSettingsIndexRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  OauthConsentRoute: OauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
