import type { FastifyInstance } from "fastify";

export const WEBHOOK_VERIFICATION_DOCS_PATH = "/docs/webhooks/verify";

export const WEBHOOK_VERIFICATION_DOCS_MARKDOWN = [
  "# Verify Helix Webhook Signatures",
  "",
  "Helix signs webhook payloads with HMAC-SHA256. The signature is sent in the `X-Helix-Signature` header as `t=<timestamp>,v1=<hex>`.",
  "",
  "To verify a webhook:",
  "",
  "1. Read the raw request body bytes before JSON parsing.",
  "2. Parse `t` and `v1` from `X-Helix-Signature`.",
  "3. Reject timestamps outside your replay tolerance, usually 300 seconds.",
  "4. Compute HMAC-SHA256 with the signing secret and message `${timestamp}.${payload}`.",
  "5. Compare the computed hex digest with `v1` using a constant-time comparison.",
  "",
  "## JavaScript",
  "",
  "```js",
  'import { createHmac, timingSafeEqual } from "node:crypto";',
  "",
  "export function verifyHelixWebhook(rawBody, signatureHeader, secret, now = Date.now()) {",
  "  const values = Object.fromEntries(",
  '    signatureHeader.split(",").map((part) => part.split("=", 2).map((value) => value.trim())),',
  "  );",
  "  const timestamp = Number(values.t);",
  "  const signature = values.v1;",
  '  if (!Number.isInteger(timestamp) || !/^[a-f0-9]{64}$/.test(signature ?? "")) return false;',
  "  if (Math.abs(Math.floor(now / 1000) - timestamp) > 300) return false;",
  "",
  '  const expected = createHmac("sha256", secret)',
  "    .update(String(timestamp))",
  '    .update(".")',
  "    .update(Buffer.isBuffer(rawBody) ? rawBody : Buffer.from(rawBody))",
  '    .digest("hex");',
  '  return timingSafeEqual(Buffer.from(signature, "hex"), Buffer.from(expected, "hex"));',
  "}",
  "```",
  "",
  "## Python",
  "",
  "```python",
  "import hashlib",
  "import hmac",
  "import time",
  "",
  "def verify_helix_webhook(raw_body: bytes, signature_header: str, secret: str) -> bool:",
  '    values = dict(part.split("=", 1) for part in signature_header.split(",") if "=" in part)',
  '    timestamp = values.get("t")',
  '    signature = values.get("v1")',
  "    if timestamp is None or signature is None:",
  "        return False",
  "    if abs(int(time.time()) - int(timestamp)) > 300:",
  "        return False",
  "",
  '    signed_payload = timestamp.encode() + b"." + raw_body',
  "    expected = hmac.new(secret.encode(), signed_payload, hashlib.sha256).hexdigest()",
  "    return hmac.compare_digest(signature, expected)",
  "```",
  "",
  "## Go",
  "",
  "```go",
  "package webhooks",
  "",
  "import (",
  '    "crypto/hmac"',
  '    "crypto/sha256"',
  '    "encoding/hex"',
  '    "strconv"',
  '    "strings"',
  '    "time"',
  ")",
  "",
  "func VerifyHelixWebhook(rawBody []byte, signatureHeader string, secret string) bool {",
  "    values := map[string]string{}",
  '    for _, part := range strings.Split(signatureHeader, ",") {',
  '        pair := strings.SplitN(part, "=", 2)',
  "        if len(pair) == 2 {",
  "            values[strings.TrimSpace(pair[0])] = strings.TrimSpace(pair[1])",
  "        }",
  "    }",
  "",
  '    timestamp, err := strconv.ParseInt(values["t"], 10, 64)',
  '    signature := values["v1"]',
  '    if err != nil || signature == "" || abs(time.Now().Unix()-timestamp) > 300 {',
  "        return false",
  "    }",
  "",
  "    mac := hmac.New(sha256.New, []byte(secret))",
  "    mac.Write([]byte(strconv.FormatInt(timestamp, 10)))",
  '    mac.Write([]byte("."))',
  "    mac.Write(rawBody)",
  "    expected := hex.EncodeToString(mac.Sum(nil))",
  "    return hmac.Equal([]byte(signature), []byte(expected))",
  "}",
  "",
  "func abs(value int64) int64 {",
  "    if value < 0 {",
  "        return -value",
  "    }",
  "    return value",
  "}",
  "```",
  "",
  "## Ruby",
  "",
  "```ruby",
  'require "openssl"',
  'require "rack/utils"',
  'require "time"',
  "",
  "def verify_helix_webhook(raw_body, signature_header, secret)",
  '  values = signature_header.split(",").each_with_object({}) do |part, parsed|',
  '    key, value = part.split("=", 2)',
  "    parsed[key.strip] = value.strip unless key.nil? || value.nil?",
  "  end",
  '  timestamp = values["t"]',
  '  signature = values["v1"]',
  "  return false if timestamp.nil? || signature.nil?",
  "  return false if (Time.now.to_i - timestamp.to_i).abs > 300",
  "",
  '  expected = OpenSSL::HMAC.hexdigest("SHA256", secret, "#{timestamp}.#{raw_body}")',
  "  Rack::Utils.secure_compare(signature, expected)",
  "end",
  "```",
  "",
  "## PHP",
  "",
  "```php",
  "<?php",
  "function verify_helix_webhook(string $rawBody, string $signatureHeader, string $secret): bool {",
  "    $values = [];",
  "    foreach (explode(',', $signatureHeader) as $part) {",
  "        $pair = explode('=', $part, 2);",
  "        if (count($pair) === 2) {",
  "            $values[trim($pair[0])] = trim($pair[1]);",
  "        }",
  "    }",
  "",
  "    $timestamp = $values['t'] ?? null;",
  "    $signature = $values['v1'] ?? null;",
  "    if ($timestamp === null || $signature === null) {",
  "        return false;",
  "    }",
  "    if (abs(time() - intval($timestamp)) > 300) {",
  "        return false;",
  "    }",
  "",
  "    $expected = hash_hmac('sha256', $timestamp . '.' . $rawBody, $secret);",
  "    return hash_equals($expected, $signature);",
  "}",
  "```",
  "",
  "Keep the signing secret private. If verification fails, return a non-2xx response and do not process the event.",
  "",
].join("\n");

export async function registerWebhookVerificationDocsRoute(app: FastifyInstance): Promise<void> {
  app.get(WEBHOOK_VERIFICATION_DOCS_PATH, async (_request, reply) =>
    reply.type("text/markdown; charset=utf-8").send(WEBHOOK_VERIFICATION_DOCS_MARKDOWN),
  );
}
