{{- if .Values.vault.csi.enabled }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.vault.csi.providerClassName }}
  labels:
    {{- include "helix.labels" . | nindent 4 }}
spec:
  provider: vault
  parameters:
    vaultAddress: {{ .Values.external.vault.address | quote }}
    roleName: {{ .Values.external.vault.role | quote }}
    objects: |
      - objectName: helix-config
        secretPath: {{ .Values.vault.secretPath | quote }}
        secretKey: config
{{- end }}
