apiVersion: api.cerbos.dev/v1
resourcePolicy:
  resource: tool
  version: default
  schemas:
    principalSchema:
      ref: cerbos:///platform/principal.json
    resourceSchema:
      ref: cerbos:///platform/tool_resource.json
  rules:
    - actions: ["*"]
      effect: EFFECT_ALLOW
      roles: ["system", "admin"]

    - actions: ["*"]
      effect: EFFECT_ALLOW
      roles: ["user", "agent", "service_account"]
      condition:
        match:
          expr: P.attr.scopes.exists(scope, scope == R.attr.permission)
