import { z } from "zod";
import { coerceNonNegInt, coercePositiveInt, optionalString, optionalUrl } from "./common.js";
export const runtimeEnv = {
  NODE_ENV: z.enum(["development", "test", "production"]).default("development"),
  DATABASE_URL: z
    .string()
    .min(1)
    .default("postgres://helix:helix_dev_password@localhost:28432/helix"),
  HELIX_MIGRATION_DATABASE_URL: optionalString,
  MIGRATION_DATABASE_URL: optionalString,
  REDIS_URL: optionalUrl,
  REDIS_TLS_CA_FILE: optionalString,
  REDIS_TLS_CERT_FILE: optionalString,
  REDIS_TLS_KEY_FILE: optionalString,
  POSTGRES_TLS_CA_FILE: optionalString,
  POSTGRES_TLS_CERT_FILE: optionalString,
  POSTGRES_TLS_KEY_FILE: optionalString,
  PORT: coercePositiveInt(3000),
  HOST: z.string().default("0.0.0.0"),
  SHUTDOWN_TIMEOUT_MS: coerceNonNegInt(50000),
  HELIX_MODE: z.enum(["single-tenant", "multi-tenant-saas"]).default("single-tenant"),
  HELIX_REGION: z.string().default("default"),
  HELIX_TRUSTED_PROXIES: optionalString,
  HELIX_ROLE: optionalString,
  HELIX_APPS: optionalString,
  HELIX_WORKSPACE_PROFILE: optionalString,
  HELIX_IMAGE: optionalString,
  HELIX_WEB_IMAGE: optionalString,
  HELIX_POSTGRES_IMAGE: optionalString,
  HELIX_NATS_IMAGE: optionalString,
  HELIX_MEILISEARCH_IMAGE: optionalString,
  HELIX_CERBOS_IMAGE: optionalString,
  HELIX_SPAMD_IMAGE: optionalString,
  LOG_LEVEL: z.string().default("info"),
  POSTGRES_POOL_MAX: coercePositiveInt(10),
  HELIX_DEFAULT_ORG_ID: z.string().default("00000000-0000-0000-0000-000000000000"),
  HELIX_PUBLIC_URL: optionalUrl,
  PUBLIC_BASE_URL: optionalUrl,
  HELIX_API_BASE_URL: optionalUrl,
  HELIX_APP_VERSION: optionalString,
  HELIX_SECURITY_TIER: optionalString,
  HELIX_CONFIG_JSON: optionalString,
  HELIX_OUTBOUND_HTTP_PROXY_URL: optionalUrl,
  HELIX_POSTGRES_ENCRYPTION_AT_REST_ATTESTED: optionalString,
  HELIX_OBJECT_STORAGE_ENCRYPTION_AT_REST_ATTESTED: optionalString,
  HELIX_BACKUP_ENCRYPTION_AT_REST_ATTESTED: optionalString,
  HELIX_DATA_ENCRYPTION_KEY: optionalString,
  HELIX_STARTUP_MIGRATION_CHECK: optionalString,
  HELIX_AGENT_WRITES_ENABLED: optionalString,
  HELIX_AGENT_WRITES_DISABLED_ORGS: optionalString,
  HELIX_DISABLED_TOOLS: optionalString,
  HELIX_GLOBAL_READ_ONLY: optionalString,
  HELIX_DRIVE_CONTENT_DEDUP: optionalString,
  HELIX_DRIVE_MULTIPART_THRESHOLD_BYTES: coercePositiveInt(8 * 1024 * 1024),
  HELIX_DRIVE_MULTIPART_PART_SIZE_BYTES: coercePositiveInt(8 * 1024 * 1024),
  HELIX_AV_MAX_SIGNATURE_AGE_MS: coercePositiveInt(48 * 60 * 60 * 1000),
  HELIX_DRIVE_AV_MAX_FILE_BYTES: coercePositiveInt(128 * 1024 * 1024),
  HELIX_DRIVE_ARCHIVE_MAX_ENTRIES: coercePositiveInt(10000),
  HELIX_DRIVE_ARCHIVE_MAX_UNCOMPRESSED_BYTES: coercePositiveInt(1024 * 1024 * 1024),
  HELIX_DRIVE_ARCHIVE_MAX_EXPANSION_RATIO: coercePositiveInt(100),
  HELIX_DRIVE_ARCHIVE_MAX_NESTED: coercePositiveInt(20),
  HELIX_DRIVE_SCAN_MAX_ATTEMPTS: coercePositiveInt(5),
  HELIX_DRIVE_SCAN_RETRY_DELAY_MS: coercePositiveInt(30000),
  HELIX_DRIVE_SCAN_RETRY_INTERVAL_MS: coercePositiveInt(10000),
  HELIX_DRIVE_SCAN_RETRY_BATCH_SIZE: coercePositiveInt(20),
  HELIX_DRIVE_SCAN_LEASE_MS: coercePositiveInt(120000),
  HELIX_DRIVE_GC_ENABLED: optionalString,
  HELIX_DRIVE_GC_INTERVAL_MS: coercePositiveInt(60 * 60 * 1000),
  HELIX_DRIVE_GC_ORPHAN_GRACE_HOURS: coercePositiveInt(24),
  HELIX_DRIVE_GC_BATCH_SIZE: coercePositiveInt(100),
  HELIX_ADMIN_DNS_VERIFICATION_ENABLED: optionalString,
  HELIX_DRIVE_SCANNER_KIND: optionalString,
  HELIX_CHROMIUM_PATH: optionalString,
  HELIX_DOCS_PDF_RENDERER: optionalString,
  HELIX_DOCS_PDF_RENDER_TIMEOUT_MS: coercePositiveInt(15000),
  NATS_URL: optionalUrl,
  NATS_USER: optionalString,
  NATS_PASSWORD: optionalString,
  NATS_TOKEN: optionalString,
  NATS_TLS_CA_FILE: optionalString,
  NATS_TLS_CERT_FILE: optionalString,
  NATS_TLS_KEY_FILE: optionalString,
  OUTBOX_BATCH_SIZE: coercePositiveInt(100),
  OUTBOX_POLL_INTERVAL_MS: coercePositiveInt(1000),
  SEARCH_EVENT_SUBJECT: z.string().default(">"),
  ENRICHMENT_EVENT_SUBJECT: z.string().default(">"),
  WEBHOOK_EVENT_SUBJECT: z.string().default(">"),
  WEBHOOK_RETRY_BATCH_SIZE: coercePositiveInt(100),
  WEBHOOK_RETRY_INTERVAL_MS: coercePositiveInt(1000),
  PENDING_ACTION_EXPIRY_INTERVAL_MS: coercePositiveInt(60000),
  PENDING_ACTION_EXPIRY_BATCH_SIZE: coercePositiveInt(500),
  TENANT_PROVISIONING_BATCH_SIZE: coercePositiveInt(10),
  TENANT_PROVISIONING_INTERVAL_MS: coercePositiveInt(5000),
  TENANT_HARD_DELETE_RETENTION_DAYS: coercePositiveInt(30),
  TENANT_HARD_DELETE_BATCH_SIZE: coercePositiveInt(10),
  TENANT_HARD_DELETE_INTERVAL_MS: coercePositiveInt(86400000),
  HELIX_BYO_STORAGE_HEALTH_REFRESH_INTERVAL_MS: coercePositiveInt(3600000),
  HELIX_BYO_STORAGE_HEALTH_REFRESH_BATCH_SIZE: coercePositiveInt(100),
  HELIX_METERING_ROLLUP_INTERVAL_MS: optionalString,
  METERING_ROLLUP_INTERVAL_MS: optionalString,
  HELIX_METERING_ROLLUP_PERIOD_BATCH_SIZE: optionalString,
  METERING_ROLLUP_PERIOD_BATCH_SIZE: optionalString,
  LEADER_ELECTION_RETRY_INTERVAL_MS: coercePositiveInt(15000),
  SEARCH_REINDEX_BATCH_SIZE: coercePositiveInt(100),
  HELIX_SECRET_ENCRYPTION_KEY: optionalString.pipe(z.string().min(32).optional()),
  HELIX_SIGNUP_RATE_LIMIT_PER_HOUR: coercePositiveInt(5),
  HELIX_SIGNUP_BLOCKED_EMAIL_DOMAINS: optionalString,
  HELIX_SIGNUP_MANUAL_REVIEW_COUNTRIES: optionalString,
  HELIX_SIGNUP_RECAPTCHA_SECRET: optionalString,
  HELIX_SIGNUP_RECAPTCHA_MIN_SCORE: z.coerce.number().min(0).max(1).default(0.5),
  HELIX_SIGNUP_RECAPTCHA_ACTION: z.string().default("signup"),
  HELIX_SIGNUP_HIBP_USER_AGENT: z.string().default("helix-signup-password-screening"),
  HELIX_SIGNUP_EMAIL_FROM: optionalString,
  HELIX_SIGNUP_EMAIL_FROM_NAME: z.string().default("Helix"),
  MAILGUN_API_KEY: optionalString,
  POSTMARK_SERVER_TOKEN: optionalString,
  HELIX_MAIL_PUBLIC_HOSTNAME: optionalString,
  MEILI_HOST: optionalUrl,
  MEILI_URL: optionalUrl,
  MEILISEARCH_URL: optionalUrl,
  MEILI_MASTER_KEY: optionalString,
  MEILI_API_KEY: optionalString,
  MEILI_INDEX_UID: optionalString,
  MEILISEARCH_API_KEY: optionalString,
  MEILISEARCH_INDEX_UID: optionalString,
  HELIX_SIEM_REGION: optionalString,
  HELIX_ADMIN_BACKUP_EXECUTE: optionalString,
  HELIX_BACKUP_DIR: optionalString,
  HELIX_BACKUP_SCRIPT: optionalString,
  HELIX_RESTORE_SCRIPT: optionalString,
  HELIX_SCIM_DOCS_URL: optionalUrl,
  HELIX_SEED_CLIENT_SECRET: optionalString,
  HELIX_LOCAL_DEMO_PASSWORD: optionalString,
  HELIX_LOCAL_DEMO_ANCHOR_DATE: optionalString,
  HELIX_LOCAL_DEMO_VOLUME_SEARCH: optionalString,
  HELIX_SMOKE_AGENT_ACTOR_ID: optionalString,
  HELIX_SMOKE_AGENT_ACTOR_TYPE: optionalString,
  HELIX_SMOKE_AGENT_CLIENT_ID: optionalString,
  HELIX_SMOKE_AGENT_CLIENT_SECRET: optionalString,
  HELIX_SMOKE_AGENT_DISPLAY_NAME: optionalString,
  HELIX_SMOKE_AGENT_EMAIL: optionalString,
  HELIX_SMOKE_AGENT_ORG_ID: optionalString,
  HELIX_SMOKE_AGENT_SCOPES: optionalString,
};
